---
title: "Class Schedule"
tbl-colwidths: [5, 10, 25, 5, 15, 5, 10, 5]
suppress-bibliography: true
format:
  html: default
---

This page contains a schedule of the topics, content, and assignments for the semester.
Note that this schedule will be updated as necessary the semester progresses, with all changes documented here.

Instructions to save the slides as PDFs can be found [here](https://quarto.org/docs/presentations/revealjs/presenting.html#print-to-pdf). The key is to hit `E` when the slides are open in your browser (ideally Chrome, but it may work in others) to toggle into PDF print mode.

Readings can be accessed using the link (when needed, through the Cornell library with a Cornell login) or on Canvas. 

| Week | Date | Topic | Slides | Reading | Homework | Quiz | Resources |
:-----:|:---------|:---------|:---------:|:------:|:--:|:---:|:---:|
| 1 | 1/21 | Class Introduction | [{{< fa sharp presentation-screen >}}](slides/lecture01-1-intro.qmd)   | [@OHagan2004-am](http://doi.wiley.com/10.1111/j.1740-9713.2004.00050.x) | [{{< fa sharp pen-field >}}](hw/hw01/hw01.qmd) | | |
|  | 1/23 | Probability Review | [{{< fa sharp presentation-screen >}}](slides/lecture01-2-probreview.qmd)  |  | | | |
| 2 | 1/26 | **Class Canceled Due To Snow**  | | [@Franconeri2021-vk](https://doi.org/10.1177/15291006211051956) | | | | |
|   | 1/28 | Exploratory Data Analysis | [{{< fa sharp presentation-screen >}}](slides/lecture02-1-eda.qmd) |  | |  |  |
|   | 1/30 | Data Visualization | [{{< fa sharp presentation-screen >}}](slides/lecture02-2-data-viz.qmd)  | | | | [Data Viz](resources/dataviz.qmd) |
| 3 | 2/02 | Linear Regression  | [{{< fa sharp presentation-screen >}}](slides/lecture03-1-linear-regression.qmd)  | [@Shmueli2010-ao](https://doi.org/10.1214/10-STS330)  | | | |
|   | 2/04 | More On Linear Regression | [{{< fa sharp presentation-screen >}}](slides/lecture03-2-linear-regression-more.qmd) |  | |  |  | |
|   | 2/06 | Linear Regression As A Probability Model | [{{< fa sharp presentation-screen >}}](slides/lecture03-3-linear-regression-mle.qmd)  | | | | | 
| 4 | 2/09 | Logistic Regression | [{{< fa sharp presentation-screen >}}](slides/lecture04-1-logistic-regression.qmd) | | [{{< fa sharp pen-field >}}](hw/hw02/hw02.qmd) | | |
|   | 2/11 | Generalized Linear Models | [{{< fa sharp presentation-screen >}}](slides/lecture04-2-glm.qmd) | | | | |
|   | 2/13 | Poisson Regression Example | [{{< fa sharp presentation-screen >}}](slides/lecture04-3-zero-inflated.qmd) | |  | Quiz 1 | |
| 5 | 2/16 | **February Break** | |  | | | | 
|  | 2/18 | Autocorrelation and Time Series | [{{< fa sharp presentation-screen >}}](slides/lecture05-1-timeseries.qmd) | [@Chandler2002-oi](https://doi.org/10.1029/2001WR000906) |  |  | |
| | 2/20 | Inference for Time Series | [{{< fa sharp presentation-screen >}}](slides/lecture05-2-timeseries-inference.qmd) | | | | |
| 6 | 2/23 | Extreme Values and Block Maxima | [{{< fa sharp presentation-screen >}}](slides/lecture06-1-modeling-extremes.qmd) | [@Arns2013-tl](http://dx.doi.org/10.1016/j.coastaleng.2013.07.003) | [{{< fa sharp pen-field >}}](hw/hw03/hw03.qmd) | | |
|   | 2/25 | Peaks Over Thresholds | [{{< fa sharp presentation-screen >}}](slides/lecture06-2-peaks-thresholds.qmd) | | | | |
|   | 2/27 | Nonstationary Extremes | [{{< fa sharp presentation-screen >}}](slides/lecture06-3-nonstationary-extremes.qmd) | | | | |
| 7 | 3/02 | Loss Functions and Scoring Rules | [{{< fa sharp presentation-screen >}}](slides/lecture07-1-model-skill.qmd) | [@Roberts2017-lr](http://dx.doi.org/10.1111/ecog.02881) | | | |
|   | 3/04 | Bias and Variance  | [{{< fa sharp presentation-screen >}}](slides/lecture07-2-bias-variance.qmd) | | | | |
|   | 3/06 | Cross-Validation | [{{< fa sharp presentation-screen >}}](slides/lecture07-3-cross-validation.qmd) | | | | |
| 8 | 3/09 | Information and Entropy | [{{< fa sharp presentation-screen >}}](slides/lecture08-1-information-models.qmd) |  [@Anderson2002-um](http://dx.doi.org/10.2307/3803155) | | | |
|   | 3/11 | Akaike Information Criterion | [{{< fa sharp presentation-screen >}}](slides/lecture08-2-information-criteria.qmd) | | | | |
|   | 3/13 | Bayesian Information Criterion | [{{< fa sharp presentation-screen >}}](slides/lecture08-3-bic.qmd) | | | Quiz 2 | |
| 9 | 3/16 | (Null) Hypothesis Testing| [{{< fa sharp presentation-screen >}}](slides/lecture09-1-nhst.qmd) | [Rosner et al (2014)](http://dx.doi.org/10.1002/2013WR014561) | [{{< fa sharp pen-field >}}](hw/hw04/hw04.qmd) | | |
|   | 3/18 | Statistical Significance | [{{< fa sharp presentation-screen >}}](slides/lecture09-2-significance.qmd)  | | | | |
|   | 3/20 | Simulation and Random Sampling | [{{< fa sharp presentation-screen >}}](slides/lecture09-3-random-simulation.qmd) | | | | |
| 10 | 3/23 | Monte Carlo | [{{< fa sharp presentation-screen >}}](slides/lecture10-1-monte-carlo.qmd) |  |  | | |
|   | 3/25 | Monte Carlo Error and Variance Reduction | [{{< fa sharp presentation-screen >}}](slides/lecture10-2-more-monte-carlo.qmd)  | | | | |
|   | 3/27 | Monte Carlo Examples| [{{< fa sharp presentation-screen >}}](slides/lecture10-3-monte-carlo-examples.qmd) | | | | | 
| 11 | 3/30 | **Spring Break** | | | | |  |
|  | 4/01 | **Spring Break** | | | | | | 
|  | 4/03 | **Spring Break** | | | | | | 
| 12  | 4/06 | Sampling Distributions | [{{< fa sharp presentation-screen >}}](slides/lecture12-1-uq.qmd) | [Kysel&yacute; (2008)](https://doi.org/10.1175/2008JAMC1763.1) | [{{< fa sharp pen-field >}}](hw/hw05/hw05.qmd)  | | | 
|    | 4/08 | The Bootstrap | [{{< fa sharp presentation-screen >}}](slides/lecture12-2-bootstrap.qmd)  | | | | | 
|    | 4/10 | Bootstrapping Structured Data | [{{< fa sharp presentation-screen >}}](slides/lecture12-3-bootstrap-structure.qmd) | | | | Quiz 3 | 
| 13 | 4/13 | Parametric Bootstrap | [{{< fa sharp presentation-screen >}}](slides/lecture13-1-parametric-bootstrap.qmd) | [Clark et al (2021)](https://doi.org/10.1029/2020wr029001) | | | | 
|  | 4/15 | Model UQ Example | [{{< fa sharp presentation-screen >}}](slides/lecture13-2-uq-model.qmd) |  | | |  | 
|  | 4/17 | Model UQ Example Continued | [{{< fa sharp presentation-screen >}}](slides/lecture13-2-uq-model.qmd) |  | | |  | 
| 14 | 4/20 | Missing Data Mechanisms | [{{< fa sharp presentation-screen >}}](slides/lecture14-1-missing-data.qmd) |  | [{{< fa sharp pen-field >}}](hw/hw06/hw06.qmd)  | |  | 
|  | 4/22 | More Missing Data | [{{< fa sharp presentation-screen >}}](slides/lecture14-2-more-missing-data.qmd) |  |  | |  | 
|  | 4/24 | Multiple Imputation | [{{< fa sharp presentation-screen >}}](slides/lecture14-3-multiple-imputation.qmd) |  |  | |  | 
| 15 | 4/27 | Mixture Models | [{{< fa sharp presentation-screen >}}](slides/lecture15-1-mixture-models.qmd) |  |  | |  | 
|    | 4/29 | Hidden Markov Models | [{{< fa sharp presentation-screen >}}](slides/lecture15-2-markov-models.qmd) |  |  | |  | 
|   | 5/01 | Hidden Markov Models (finished) | [{{< fa sharp presentation-screen >}}](slides/lecture15-2-markov-models.qmd) |  |  | Quiz 4 |  | 