<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Syllabus – Environmental Data Analysis &amp; Simulation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./_assets/logos/favicon.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-5cf72458b51e521e41f1ac40627354c5.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-fb17626478aa78ce15980021f2baceac.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- MathJax 3 -->
<script>
window.MathJax = {
    tex: {
      tags: 'ams'
    }
  };
</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<meta property="og:title" content="Syllabus – Environmental Data Analysis &amp; Simulation">
<meta property="og:description" content="Homepage for the Spring 2026 version of BEE 4850/5850, Environmental Data Analysis &amp; Simulation, at Cornell University.">
<meta property="og:site_name" content="Environmental Data Analysis &amp; Simulation">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">BEE 4850/5850</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-info" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Info</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-info">    
        <li>
    <a class="dropdown-item" href="./syllabus.html">
 <span class="dropdown-text">Syllabus</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./policies/index.html">
 <span class="dropdown-text">Course Policies</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./faq/index.html">
 <span class="dropdown-text">FAQ</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./setup/index.html">
 <span class="dropdown-text">Setup</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./schedule.html"> 
<span class="menu-text">Class Schedule</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-coursework" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Coursework</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-coursework">    
        <li>
    <a class="dropdown-item" href="./labs/index.html">
 <span class="dropdown-text">Labs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./hw/index.html">
 <span class="dropdown-text">Homework Assignments</span></a>
  </li>  
        <li class="dropdown-header">lit_critique/index.qmd</li>
        <li>
    <a class="dropdown-item" href="./project/index.html">
 <span class="dropdown-text">Term Project</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-resources" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Resources</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-resources">    
        <li>
    <a class="dropdown-item" href="./tutorials/index.html">
 <span class="dropdown-text">Tutorials</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./resources/general.html">
 <span class="dropdown-text">General Resources</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./resources/julia.html">
 <span class="dropdown-text">Julia Resources</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./resources/ai.html">
 <span class="dropdown-text">Generative AI and LLMs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./resources/github.html">
 <span class="dropdown-text">GitHub Resources</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./resources/markdown.html">
 <span class="dropdown-text">Markdown Resources</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./resources/dataviz.html">
 <span class="dropdown-text">Data Visualization</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/bee-envdata-cornell/spring2026/"> 
<span class="menu-text"><i class="fa-brands fa-github" aria-label="github"></i> GitHub</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://canvas.cornell.edu"> 
<span class="menu-text"><i class="fa-regular fa-notebook" aria-label="notebook"></i> Canvas</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://edstem.org"> 
<span class="menu-text"><i class="fa-regular fa-comments" aria-label="comments"></i> Ed</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://gradescope.com"> 
<span class="menu-text"><i class="fa-regular fa-chart-simple" aria-label="chart-simple"></i> Gradescope</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#course-overview" id="toc-course-overview" class="nav-link active" data-scroll-target="#course-overview">Course Overview</a>
  <ul class="collapse">
  <li><a href="#course-description" id="toc-course-description" class="nav-link" data-scroll-target="#course-description">Course Description</a></li>
  </ul></li>
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link" data-scroll-target="#learning-outcomes">Learning Outcomes</a></li>
  <li><a href="#prerequisites-preparation" id="toc-prerequisites-preparation" class="nav-link" data-scroll-target="#prerequisites-preparation">Prerequisites &amp; Preparation</a></li>
  <li><a href="#typical-topics" id="toc-typical-topics" class="nav-link" data-scroll-target="#typical-topics">Typical Topics</a></li>
  <li><a href="#course-meetings" id="toc-course-meetings" class="nav-link" data-scroll-target="#course-meetings">Course Meetings</a></li>
  <li><a href="#course-philosophy-and-expectations" id="toc-course-philosophy-and-expectations" class="nav-link" data-scroll-target="#course-philosophy-and-expectations">Course Philosophy and Expectations</a></li>
  <li><a href="#textbooks-and-course-materials" id="toc-textbooks-and-course-materials" class="nav-link" data-scroll-target="#textbooks-and-course-materials">Textbooks and Course Materials</a></li>
  <li><a href="#community" id="toc-community" class="nav-link" data-scroll-target="#community">Community</a>
  <ul class="collapse">
  <li><a href="#diversity-and-inclusion" id="toc-diversity-and-inclusion" class="nav-link" data-scroll-target="#diversity-and-inclusion">Diversity and Inclusion</a></li>
  <li><a href="#student-accomodations" id="toc-student-accomodations" class="nav-link" data-scroll-target="#student-accomodations">Student Accomodations</a></li>
  <li><a href="#course-communications" id="toc-course-communications" class="nav-link" data-scroll-target="#course-communications">Course Communications</a></li>
  <li><a href="#mental-health-resources" id="toc-mental-health-resources" class="nav-link" data-scroll-target="#mental-health-resources">Mental Health Resources</a></li>
  </ul></li>
  <li><a href="#course-policies" id="toc-course-policies" class="nav-link" data-scroll-target="#course-policies">Course Policies</a>
  <ul class="collapse">
  <li><a href="#attendance" id="toc-attendance" class="nav-link" data-scroll-target="#attendance">Attendance</a></li>
  <li><a href="#mask-policies" id="toc-mask-policies" class="nav-link" data-scroll-target="#mask-policies">Mask Policies</a></li>
  <li><a href="#academic-integrity" id="toc-academic-integrity" class="nav-link" data-scroll-target="#academic-integrity">Academic Integrity</a></li>
  <li><a href="#external-resources" id="toc-external-resources" class="nav-link" data-scroll-target="#external-resources">External Resources</a></li>
  <li><a href="#aiml-resource-policy" id="toc-aiml-resource-policy" class="nav-link" data-scroll-target="#aiml-resource-policy">AI/ML Resource Policy</a></li>
  <li><a href="#late-work-policy" id="toc-late-work-policy" class="nav-link" data-scroll-target="#late-work-policy">Late Work Policy</a></li>
  <li><a href="#regrade-requests" id="toc-regrade-requests" class="nav-link" data-scroll-target="#regrade-requests">Regrade Requests</a></li>
  <li><a href="#office-hours" id="toc-office-hours" class="nav-link" data-scroll-target="#office-hours">Office Hours</a></li>
  </ul></li>
  <li><a href="#assessments" id="toc-assessments" class="nav-link" data-scroll-target="#assessments">Assessments</a>
  <ul class="collapse">
  <li><a href="#technologies" id="toc-technologies" class="nav-link" data-scroll-target="#technologies">Technologies</a></li>
  <li><a href="#grading" id="toc-grading" class="nav-link" data-scroll-target="#grading">Grading</a></li>
  <li><a href="#participation" id="toc-participation" class="nav-link" data-scroll-target="#participation">Participation</a></li>
  <li><a href="#quizzes" id="toc-quizzes" class="nav-link" data-scroll-target="#quizzes">Quizzes</a></li>
  <li><a href="#labs" id="toc-labs" class="nav-link" data-scroll-target="#labs">Labs</a></li>
  <li><a href="#literature-critique" id="toc-literature-critique" class="nav-link" data-scroll-target="#literature-critique">Literature Critique</a></li>
  <li><a href="#readings" id="toc-readings" class="nav-link" data-scroll-target="#readings">Readings</a></li>
  <li><a href="#homework-assignments" id="toc-homework-assignments" class="nav-link" data-scroll-target="#homework-assignments">Homework Assignments</a></li>
  <li><a href="#prelims" id="toc-prelims" class="nav-link" data-scroll-target="#prelims">Prelims</a></li>
  <li><a href="#term-project" id="toc-term-project" class="nav-link" data-scroll-target="#term-project">Term Project</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/bee-envdata-cornell/spring2026/edit/main/syllabus.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/bee-envdata-cornell/spring2026/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div><div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="syllabus-BEE4850-SP26.pdf"><i class="bi bi-file-pdf"></i>Typst</a></li><li><a href="syllabus-BEE4850-SP26.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Syllabus</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="course-overview" class="level2">
<h2 class="anchored" data-anchor-id="course-overview">Course Overview</h2>
<p>This is a 3 credit course offered as an elective.</p>
<div class="columns course-details">
<div class="column" style="width:33%;">
<section id="instructor" class="level3">
<h3 class="anchored" data-anchor-id="instructor">Instructor</h3>
<ul>
<li><i class="fa-sharp fa-user" title="Name" aria-label="user"></i> <span class="ms-1"><a href="https://viveks.me">Vivek Srikrishnan</a></span></li>
<li><i class="fa-sharp fa-envelope" title="Email" aria-label="envelope"></i> <span class="ms-1"><a href="mailto:vs498@cornell.edu">vs498@cornell.edu</a></span></li>
<li><i class="fa-sharp fa-building" title="Office" aria-label="building"></i> <span class="ms-2">318 Riley-Robb Hall</span></li>
</ul>
</section>
</div><div class="column" style="width:33%;">
<section id="ta" class="level3">
<h3 class="anchored" data-anchor-id="ta">TA</h3>
<ul>
<li><i class="fa-sharp fa-user" title="Name" aria-label="user"></i> <span class="ms-1">TBD</span></li>
<li><i class="fa-sharp fa-envelope" title="Email" aria-label="envelope"></i> <span class="ms-1"><a href="mailto:TBD">TBD</a></span></li>
<li><i class="fa-sharp fa-building" title="Office" aria-label="building"></i> <span class="ms-2">TBD</span></li>
</ul>
</section>
</div><div class="column" style="width:33%;">
<section id="meetings" class="level3">
<h3 class="anchored" data-anchor-id="meetings">Meetings</h3>
<ul>
<li><i class="fa-sharp fa-calendar" title="Class Days" aria-label="calendar"></i> MWF</li>
<li><i class="fa-sharp fa-clock" title="Class Time" aria-label="clock"></i> 11:15-12:05</li>
<li><i class="fa-sharp fa-university" title="Class Location" aria-label="university"></i> 401 Riley-Robb Hall</li>
</ul>
</section>
</div>
</div>
<section id="course-description" class="level3">
<h3 class="anchored" data-anchor-id="course-description">Course Description</h3>
<p>Understanding data is an increasingly integral part of working with environmental systems. Data analysis is a critical part of understanding system dynamics and projecting future conditions and outcomes. This course will provide an overview of a generative approach to environmental data analysis, which uses simulation and assessments of predictive performance to provide insight into the structure of data and its data-generating process. We will discuss exploratory analysis and visualization, model development and fitting, uncertainty quantification, and model assessment. The goal is to provide students with a framework and an initial toolkit of methods that they can use to formulate and update hypotheses about data and models. Students will actively analyze and use real data from a variety of environmental systems.</p>
<p>In particular, over the course of the semester, we will:</p>
<ul>
<li>conduct exploratory analyses of environmental datasets;</li>
<li>discuss best practices for and complexities of data visualization;</li>
<li>calibrate statistical and process-based numerical models using environmental data;</li>
<li>use simulations from calibrated models to identify key sources of uncertainty and model error;</li>
<li>assess model fit and adequacy through predictive ability.</li>
</ul>
</section>
</section>
<section id="learning-outcomes" class="level2">
<h2 class="anchored" data-anchor-id="learning-outcomes">Learning Outcomes</h2>
<p>After completing this class, students will be able to:</p>
<ul>
<li>conduct exploratory analyses of data, including creating, interpreting, and critiquing data visualizations;</li>
<li>calibrate environmental models to observations, including missing data;</li>
<li>quantify and propagate uncertainty using simulation methods such as the bootstrap and Monte Carlo;</li>
<li>assess model adequacy and performance using predictive simulations;</li>
<li>evaluate evidence for and against hypotheses about environmental systems using model simulations.</li>
</ul>
</section>
<section id="prerequisites-preparation" class="level2">
<h2 class="anchored" data-anchor-id="prerequisites-preparation">Prerequisites &amp; Preparation</h2>
<p>The following courses/material would be ideal preparation:</p>
<ul>
<li>One course in programming (<em>e.g.</em> CS 1110, 1112 or ENGRD/CEE 3200)</li>
<li>One course in probability or statistics (ENGRD 2700, CEE 3040, or equivalent)</li>
</ul>
<p>In the absence of one or more these prerequisites, you can seek the permission of instructor.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>What If My Programming or Stats Skills Are Rusty?
</div>
</div>
<div class="callout-body-container callout-body">
<p>If your programming or statistics skills are a little rusty, don’t worry! We will review concepts and build skills as needed.</p>
</div>
</div>
</section>
<section id="typical-topics" class="level2">
<h2 class="anchored" data-anchor-id="typical-topics">Typical Topics</h2>
<ul>
<li>Introduction to exploratory data analysis;</li>
<li>Principles of data visualization;</li>
<li>Probability models for data;</li>
<li>Extreme values;</li>
<li>Missing data;</li>
<li>Model fitting;</li>
<li>Uncertainty quantification with the bootstrap and Monte Carlo;</li>
<li>Model assessment and comparison.</li>
</ul>
</section>
<section id="course-meetings" class="level2">
<h2 class="anchored" data-anchor-id="course-meetings">Course Meetings</h2>
<p>This course meets MWF from 11:15-12:05 in 401 Riley-Robb. In addition to the course meetings (a total of 42 lectures, 50 minutes each), the final project will be due during the university finals period. Students can expect to devote, on average, 6 hours of effort during the exam period.</p>
</section>
<section id="course-philosophy-and-expectations" class="level2">
<h2 class="anchored" data-anchor-id="course-philosophy-and-expectations">Course Philosophy and Expectations</h2>
<p>The goal of our course is to help you gain competancy and knowledge in the area of data analysis. This involves a dual responsibility on the part of the instructor and the student. As the instructor, my responsibility is to provide you with a structure and opportunity to learn. To this end, I will commit to:</p>
<ul>
<li>provide organized and focused lectures, in-class activities, and assignments;</li>
<li>encourage students to regularly evaluate and provide feedback on the course;</li>
<li>manage the classroom atmosphere to promote learning;</li>
<li>schedule sufficient out-of-class contact opportunities, such as office hours;</li>
<li>allow adequate time for assignment completion;</li>
<li>make lecture materials, class policies, activities, and assignments accessible to students.</li>
</ul>
<p>I encourage you to discuss any concerns with me during office hours or through a course communications channel! Please let me know if you do not feel that I am holding up my end of the bargain.</p>
<p>Students can optimize their performance in the course by:</p>
<ul>
<li>attending all lectures;</li>
<li>doing any required preparatory work before class;</li>
<li>actively participating in online and in-class discussions;</li>
<li>beginning assignments and other work early;</li>
<li>and attending office hours as needed.</li>
</ul>
</section>
<section id="textbooks-and-course-materials" class="level2">
<h2 class="anchored" data-anchor-id="textbooks-and-course-materials">Textbooks and Course Materials</h2>
<p>There is no required text for this class, and all course materials will be made available on the <a href="https://envdata.viveks.me/spring2026/">course website</a> or through the Cornell library. However, the following books might be useful as a supplement to/expansion on the topics covered in class:</p>
<ul>
<li>Gelman, A., Carlin, J. B., Stern, H. S., Dunson, D. B., Vehtari, A., &amp; Rubin, D. B. (2013). <em>Bayesian Data Analysis</em> (3rd ed.). <a href="http://www.stat.columbia.edu/~gelman/book/BDA3.pdf" class="uri">http://www.stat.columbia.edu/~gelman/book/BDA3.pdf</a></li>
<li>McElreath, R. (2020). <em>Statistical Rethinking: A Bayesian Course with Examples in R and Stan</em> (2nd ed.). <a href="https://xcelab.net/rm/" class="uri">https://xcelab.net/rm/</a></li>
<li>D’Agostini, G. (2003). <em>Bayesian Reasoning in Data Analysis: A Critical Introduction</em>.</li>
<li>Gelman, A., Hill, J., &amp; Vehtari, A. (2020). <em>Regression and Other Stories</em>. <a href="https://avehtari.github.io/ROS-Examples/index.html" class="uri">https://avehtari.github.io/ROS-Examples/index.html</a></li>
</ul>
</section>
<section id="community" class="level2">
<h2 class="anchored" data-anchor-id="community">Community</h2>
<section id="diversity-and-inclusion" class="level3">
<h3 class="anchored" data-anchor-id="diversity-and-inclusion">Diversity and Inclusion</h3>
<p>Our goal in this class is to foster an inclusive learning environment and make everyone feel comfortable in the classroom, regardless of social identity, background, and specific learning needs. As engineers, our work touches on many critical aspects of society, and questions of inclusion and social justice cannot be separated from considerations of systems analysis, objective selection, risk analysis, and trade-offs.</p>
<p>In all communications and interactions with each other, members of this class community (students and instructors) are expected to be respectful and inclusive. In this spirit, we ask all participants to:</p>
<ul>
<li>share their experiences, values, and beliefs;</li>
<li>be open to and respectful of the views of others; and</li>
<li>value each other’s opinions and communicate in a respectful manner.</li>
</ul>
<p>Please let me know if you feel any aspect(s) of class could be made more inclusive. Please also share any preferred name(s) and/or your pronouns with me if you wish: I use he/him/his, and you can refer to me either as Vivek or Prof.&nbsp;Srikrishnan.</p>
<p>Please be professional and courteous on all course interactions and platforms, and (except in designated off-topic boards or forums) please keep all online discussion relevant to the course. We do not anticipate this as a problem given our experience; almost all students in almost all classes meet these expectations. However, even a single incident can do serious damage to the learning environment and the well-being of your fellow students.</p>
<p>Sexually explicit, harassing, threatening, bullying, trolling, racist, sexist, homophobic, transphobic, or otherwise grossly unprofessional content will be removed. Anyone behaving in these fashions or posting such content will be blocked/banned from the appropriate platform and may be given an F if they are consistently disruptive.</p>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Please, Be Excellent To Teach Other
</div>
</div>
<div class="callout-body-container callout-body">
<p>We all make mistakes in our communications with one another, both when speaking and listening. Be mindful of how spoken or written language might be misunderstood, and be aware that, for a variety of reasons, how others perceive your words and actions may not be exactly how you intended them. At the same time, it is also essential that we be respectful and interpret each other’s comments and actions in good faith.</p>
</div>
</div>
</section>
<section id="student-accomodations" class="level3">
<h3 class="anchored" data-anchor-id="student-accomodations">Student Accomodations</h3>
<p>Let me know if you have any access barriers in this course, whether they relate to course materials, assignments, or communications. If any special accomodations would help you navigate any barriers and improve your chances of success, please exercise your right to those accomodations and reach out to me as early as possible with your <a href="https://sds.cornell.edu/">Student Disability Services</a> (SDS) accomodation letter. This will ensure that we have enough time to make appropriate arrangements.</p>
<p>If you need more immediate accomodations, but do not yet have a letter, please let me know and then follow up with SDS.</p>
</section>
<section id="course-communications" class="level3">
<h3 class="anchored" data-anchor-id="course-communications">Course Communications</h3>
<p>Most course communications will occur via <a href="https://edstem.org">Ed Discussion</a>. Public Ed posts are generally preferred to private posts or emails, as other students can benefit from the discussions. If you would like to discuss something privately, please do reach out through email or a private Ed post (which will only be viewable by you and the course staff).</p>
<p>Announcements will be made on the course website and in Ed. Emergency announcements will also be made on Canvas.</p>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Ed Tips
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Do not take screenshots of code</strong>. I will not respond. Screenshots can be difficult to read and limit accessibility. Put your code on GitHub, share the link, and point to specific line numbers if relevant, or provide a <em>simple</em>, self-contained example of the problem you’re running into.</li>
<li>If you wait until the day an assignment is due (or even late the previous night) to ask a question on Ed, there is a strong chance that I will not see your post prior to the deadline.</li>
<li>If you see unanswered questions and you have some insight, please answer! This class will work best when we all work together as a community.</li>
</ul>
</div>
</div>
</section>
<section id="mental-health-resources" class="level3">
<h3 class="anchored" data-anchor-id="mental-health-resources">Mental Health Resources</h3>
<p>We all have to take care of our mental health, just as we would our physical health. As a student, you may experience a range of issues which can negatively impact your mental health. Please do not ignore any of these stressors, or feel like you have to navigate these challenges alone! You are part of a community of students, faculty, and staff, who have a responsibility to look for one another’s well-being. If you are struggling with managing your mental health, or if you believe a classmate may be struggling, please reach out to the course instructor, the TA, or, for broader support, please take advantage of <a href="https://mentalhealth.cornell.edu/">Cornell’s mental health resources</a>.</p>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Mental Health And This Class
</div>
</div>
<div class="callout-body-container callout-body">
<p>I am not a trained counselor, but I am here to support you in whatever capacity we can. You should never feel that you need to push yourself past your limits to complete any assignment for this class or any other. If we need to make modifications to the course or assignment schedule, you can certainly reach out to me, and all relevant discussions will be kept strictly confidential.</p>
</div>
</div>
</section>
</section>
<section id="course-policies" class="level2">
<h2 class="anchored" data-anchor-id="course-policies">Course Policies</h2>
<p>Many policies below (including grading policies) are broken out and discussed further on the course website. Lack of familiarity with any of these policies is not an excuse for violating any of them.</p>
<section id="attendance" class="level3">
<h3 class="anchored" data-anchor-id="attendance">Attendance</h3>
<p>Attendance is not <em>required</em>, but in general, students who attend class regularly will do better and get more out of the class than students who do not. Your class participation grade will reflect both the quantity and quality of your participation, only some of which can occur asynchronously. I will put as many course materials, such as lecture notes and announcements, as possible online, but viewing materials online is not the same as active participation and engagement. Life happens, of course, and this may lead you to miss class. Let me know if you need any appropriate arrangements ahead of time.</p>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>What If I’m Sick?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Please stay home if you’re feeling sick! This is beneficial for both for your own recovery and the health and safety of your classmates. We will also make any necessary arrangements for you to stay on top of the class material and if whatever is going on will negatively impact your grade, for example by causing you to be unable to submit an assignment on time.</p>
</div>
</div>
</section>
<section id="mask-policies" class="level3">
<h3 class="anchored" data-anchor-id="mask-policies">Mask Policies</h3>
<p>Please stay home and rest if you have symptoms of COVID-19 or any other respiratory illness. No masking will be required, but please be respectful of others who may wear masks or take other precautions to avoid illness. This policy may change if there is another outbreak of COVID-19 (or other illness), but will be kept consistent with broader Cornell mask policies.</p>
</section>
<section id="academic-integrity" class="level3">
<h3 class="anchored" data-anchor-id="academic-integrity">Academic Integrity</h3>
<div class="callout callout-style-simple callout-important">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>TL;DR</strong>: Don’t cheat, copy, or plagiarize!</p>
</div>
</div>
</div>
<p>This class is designed to encourage collaboration, and students are encouraged to discuss their work with other students. However, I expect students to abide by the <a href="http://theuniversityfaculty.cornell.edu/academic-integrity/">Cornell University Code of Academic Integrity</a> in all aspects of this class. <strong>All work submitted must represent the students’ own work and understanding</strong>, whether individually or as a group (depending on the particulars of the assignment). This includes analyses, code, software runs, and reports. Engineering as a profession relies upon the honesty and integrity of its practitioners (see <em>e.g.</em> the <a href="https://www.asce.org/-/media/asce-images-and-files/career-and-growth/ethics/documents/asce-code-ethics.pdf">American Society for Civil Engineers’ Code of Ethics</a>).</p>
</section>
<section id="external-resources" class="level3">
<h3 class="anchored" data-anchor-id="external-resources">External Resources</h3>
<p>The collaborative environment in this class <strong>should not be viewed as an invitation for plagiarism</strong>. Plagiarism occurs when a writer intentionally misrepresents another’s words or ideas (including code!) as their own without acknowledging the source. <strong>All</strong> external resources which are consulted while working on an assignment should be referenced, including other students and faculty with whom the assignment is discussed. You will never be penalized for consulting an external source for help and referencing it, but plagiarism will result in a zero for that assignment as well as the potential for your case to be passed on for additional disciplinary action.</p>
</section>
<section id="aiml-resource-policy" class="level3">
<h3 class="anchored" data-anchor-id="aiml-resource-policy">AI/ML Resource Policy</h3>
<p>Large language models (LLMs), such as GPT, and other generative AI models are powerful tools for predicting text and code patterns. However, while they can save time (though you’d be surprised at how little time their careful use saves), they often make mistakes that can be hard to detect or fail to communicate key ideas or insights at the expense of more general and banal text. As you are likely to encounter an ever-widening use of these tools when you leave Cornell, it is critical that you learn how to use these tools responsibly and effectively.</p>
<p>However, this class will not focus on teaching you how to use LLMs responsibly; we assume that if you are using these tools, you are doing so in a way which benefits your learning and helps you communicate your already-existing understanding, rather than substituting for it. You are <strong>generally</strong> permitted to use these tools, but you are ultimately responsible for guaranteeing, understanding, and interpreting your results. If you submit work that was LLM generated, and this work receives a poor grade due to the LLM’s inability to demonstrate understanding, your grade will reflect that substantive assessment.</p>
<p>General guidelines for AI/ML use:</p>
<ul>
<li><strong>AI tools for code</strong>: You may use LLM tools for code development and debugging, particularly for translating between other languages that you already have a better knowledge of (<em>e.g.</em> Python) and Julia. However, LLMs often make bad decisions about how to structure code, can introduce bugs (including suggesting packages that do not exist or outdated syntax), and can mislead you about what your code is doing. You are responsible for understanding and debugging any code involved in solving computational exercises. Notably, if you ask for help debugging LLM-generated code, this will not be possible unless you have already developed your own understanding of what each piece of the code does (or should do) and which parts work and don’t work.</li>
<li><strong>AI tools for writing</strong>: LLMs <strong>should not be used to generate text that you submit as your own work</strong>. The point of written assessments (including model derivations and interpretations) is to stimulate your own critical thinking and mathematical skills, and you short-cut this process by substituting LLM use for your own process of formulating and articulating ideas. Even using LLMs to do the initial writing and editing that output will result in shallower thinking. As we are not teaching you in this class to critically engage with LLMs, However, you <em>may</em> use LLMs or similar tools (<em>e.g.</em> Grammarly) to help you edit your writing. As mentioned before, you are ultimately responsible for the content of any work you turn in: if a tool used to edit grammar changed the substance of your writing, you will be responsible for the submission.</li>
</ul>
<p>To distinguish between these permissible and impermissible uses, you are required to cite your use of the tool (as with any other external reference). In particular, you must disclose how you use the LLM and how you incorporated any output into your final submission. <strong>Failure to fully reference the interaction, as described above, will be treated as plagiarism and referred to the University accordingly.</strong> If you have any questions about whether your planned use of an AI/ML tool complies with the academic integrity policy, please consult a member of the course staff ahead of its use.</p>
</section>
<section id="late-work-policy" class="level3">
<h3 class="anchored" data-anchor-id="late-work-policy">Late Work Policy</h3>
<p>In general, late work can be submitted up to 24 hours late at a 50% penalty, and will not be accepted after that point. This policy may seem strict, but allows for prompt release of solutions and discussion of assignments. Please reach out <em>as soon as possible</em> (ideally before the due date) if legitimate circumstances emerge which prevent you from submitting work within 24 hours of the due date; we will make accomodations for approved reasons, which might included a limited extension or dropping the assignment.</p>
</section>
<section id="regrade-requests" class="level3">
<h3 class="anchored" data-anchor-id="regrade-requests">Regrade Requests</h3>
<p>Regrade requests can be submitted up to one week after the graded work is released on Gradescope.</p>
<p>All regrade requests must include a <strong>brief</strong> justification for the request or they will not be considered. Good justifications include (but are not limited to): - <em>My answer agrees with the posted solution, but I still lost points.</em> - <em>I lost 4 points for something, but the rubric says it should only be worth 2 points.</em> - <em>You took points off for something, but it’s right here.</em> - <em>My answer is correct, even though it does not match the posted solution; here is an explanation</em>. - <em>There is no explanation for my grade</em>. - <em>I got a perfect score, but my solution has a mistake</em> (you will receive extra credit for this! see below!) - <em>There is a major error in the posted solution; here is an explanation</em> (full credit for everyone, but Prof.&nbsp;Srikrishnan will decide what constitutes a “major error”! see below!).</p>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>We Can Only Grade What You Submitted
</div>
</div>
<div class="callout-body-container callout-body">
<p>All regrades will be assessed based only on the submitted work. You cannot get a higher grade by explanating what you meant (either in person or online) or by adding information or reasoning to what is submitted after the fact. The goal of the regrade is to draw attention to a potential grading problem, not to supplement the submission.</p>
</div>
</div>
<p>The first regrade request for any submission will be handled by the person who graded that homework problem. The first regrade request for any exam submission will be handled by whoever graded that exam problem. If the submission was graded by the TA, additional regrade requests for the same submission will be handled directly by the instructor. Once Prof.&nbsp;Srikrishnan issues a final response to a regrade request, further requests for that submission will be ignored.</p>
<div class="callout callout-style-simple callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Regrade Requests Can Be A Gamble!
</div>
</div>
<div class="callout-body-container callout-body">
<p>While you should submit regrade requests for legitimate errors, using them for fishing expeditions can also result in lost points if the TA or Prof.&nbsp;Srikrishnan decide that your initial grade was too lenient or if additional errors are identified.</p>
</div>
</div>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>What If I Find A Different Type of Mistake?
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>If you submit a regrade request <em>correctly</em> reporting that a problem was graded too leniently — that is, that your score was higher than it should be based on the rubric — your score will be increased by the difference. For example, if your original score on a problem was 8/10 and you successfully argue that your score should have been 3/10, your new score will be 13/10. However, don’t fish — your grade might be lowered if the TA finds an independent mistake while regrading.</li>
<li>If a significant error is discovered in a posted homework solution or in the exam solutions, everyone will in the class will receive <em>full</em> credit for the (sub)problem. Prof.&nbsp;Srikrishnan will decide what is “significant”.</li>
</ul>
</div>
</div>
</section>
<section id="office-hours" class="level3">
<h3 class="anchored" data-anchor-id="office-hours">Office Hours</h3>
<p>Office hours with both Prof.&nbsp;Srikrishnan and the TA will be available each week at times specified at the top of this syllabus. Changes to the office hour schedule (cancellations/rescheduling) will be announced in class and on Ed Discussion.</p>
<p>Office hours are intended to help all students who attend. This time is limited, and is best spent on issues that are relevant to as many students as possible. While we will do our best to answer individual questions, students asking us to verify or debug homework solutions or help with syntax will have the lowest priority (<strong>but please do ask about how to verify or debug your own solutions!</strong>). However, we are happy to discuss conceptual approaches to solving homework problems, which may help to reveal bugs.</p>
<p>Space at office hours can be limited (we may shift to the conference room in 316 Riley-Robb if offices are full and it is available). If the room is crowded and you can find an alternative source of assistance, or if your question is low priority (<em>e.g.</em> debugging) please be kind and make room for others.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>What If I Can’t Make Office Hours?
</div>
</div>
<div class="callout-body-container callout-body">
<p>While we will try to select office hours that work for as much of the class as possible, both the course staff and students have busy schedules and no time will work for everyone. <strong>If you need help outside of office hours (<em>e.g.</em> office hours do not fit your schedule), please send an email to the TA or Prof.&nbsp;Srikrishnan as soon as possible</strong>. These requests may not be accepted on short notice (<em>e.g.</em> if you have a question about a homework due on Thursday and send a request on the immediately prior Wednesday; schedules for course staff may already be full). We recommend starting your homework promptly so you can take advantage of office hours or make an appointment over a longer period.</p>
</div>
</div>
</section>
</section>
<section id="assessments" class="level2">
<h2 class="anchored" data-anchor-id="assessments">Assessments</h2>
<section id="technologies" class="level3">
<h3 class="anchored" data-anchor-id="technologies">Technologies</h3>
<p>We will use Canvas as a gradebook, and to distribute PDFs of readings (which also be made available through the website when possible, via the Cornell library). Ed Discussion will be used for course communications. Assignments will be submitted and graded in Gradescope.</p>
<p>Students can use any programming language they like to solve problems, though we will make notebooks and package environments available for Julia (which may help structure your assignments if you use a different language) via GitHub. If students use a language other than Julia, we may limited in the programming assistance we can provide (though we’re happy to try to help!).</p>
<p>We recommend students create a GitHub account and use GitHub to version control and share their code throughout the semester.</p>
</section>
<section id="grading" class="level3">
<h3 class="anchored" data-anchor-id="grading">Grading</h3>
<p>Final grades will be computed based on the following assessment weights:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Assessment</th>
<th style="text-align: right;">Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Labs</td>
<td style="text-align: right;">10%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Quizzes</td>
<td style="text-align: right;">5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Participation (4850)/Literature Critique (5850)</td>
<td style="text-align: right;">10%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Readings</td>
<td style="text-align: right;">10%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Homework Assignments</td>
<td style="text-align: right;">15%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Prelims</td>
<td style="text-align: right;">30%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Term Project</td>
<td style="text-align: right;">20%</td>
</tr>
</tbody>
</table>
<p>The following grading scale will be used to convert the numerical weighted average to letter grades:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Grade</th>
<th style="text-align: left;">Range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A+</td>
<td style="text-align: left;">97–100</td>
</tr>
<tr class="even">
<td style="text-align: center;">A</td>
<td style="text-align: left;">93–97</td>
</tr>
<tr class="odd">
<td style="text-align: center;">A-</td>
<td style="text-align: left;">90–93</td>
</tr>
<tr class="even">
<td style="text-align: center;">B+</td>
<td style="text-align: left;">87–90</td>
</tr>
<tr class="odd">
<td style="text-align: center;">B</td>
<td style="text-align: left;">83–87</td>
</tr>
<tr class="even">
<td style="text-align: center;">B-</td>
<td style="text-align: left;">80–83</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C+</td>
<td style="text-align: left;">77–80</td>
</tr>
<tr class="even">
<td style="text-align: center;">C</td>
<td style="text-align: left;">73–77</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C-</td>
<td style="text-align: left;">70–73</td>
</tr>
<tr class="even">
<td style="text-align: center;">D+</td>
<td style="text-align: left;">67–70</td>
</tr>
<tr class="odd">
<td style="text-align: center;">D</td>
<td style="text-align: left;">63–67</td>
</tr>
<tr class="even">
<td style="text-align: center;">D-</td>
<td style="text-align: left;">60–63</td>
</tr>
<tr class="odd">
<td style="text-align: center;">F</td>
<td style="text-align: left;">&lt; 60</td>
</tr>
</tbody>
</table>
</section>
<section id="participation" class="level3">
<h3 class="anchored" data-anchor-id="participation">Participation</h3>
<p>Participating fully in the class allows you to gain more from the class and contribute more to the learning of your classmates. Some ways to participate include:</p>
<ul>
<li>Asking questions in class or on Ed;</li>
<li>Answering questions in class or on Ed;</li>
<li>Actively engaging in in-class activities;</li>
<li>Coming to office hours.</li>
</ul>
<p>Note that just passively attending class will not yield full participation points. Participation points are not free: you are likely to lose points if you consistently skip class or do not ask or answer questions online or in person. At the end of the term, you will be asked to evaluate your own participation over the course of the semester, in addition to my documentation of your participation. Participation is a component of the grade for students enrolled in BEE 4850.</p>
</section>
<section id="quizzes" class="level3">
<h3 class="anchored" data-anchor-id="quizzes">Quizzes</h3>
<p>Quizzes will be assigned in Gradescope most weeks based on recently discussed content. These will be relatively short and are intended to consolidate material recently discussed in class. The quizzes will be released after Wednesday’s class and will be due prior to next Monday’s. Quizzes can be retaken as many times as are desired prior to the submission deadline. They may consist of multiple choice questions or questions involving small mathematical, computational, or open-ended problems. One quiz will be dropped automatically (this is intended to account for a week in which you forget or are too busy to submit).</p>
</section>
<section id="labs" class="level3">
<h3 class="anchored" data-anchor-id="labs">Labs</h3>
<p>Several class periods (typically on Fridays) will be dedicated to in-class labs. Students will be given worksheets and/or Jupyter notebooks aimed at getting hands-on practice with the prior lecture topic(s). Lab writeups will be due before the class meeting the following Monday after the lab period. They will be graded primarily on evidence of effort rather than correctness. One lab assignment will be automatically dropped.</p>
</section>
<section id="literature-critique" class="level3">
<h3 class="anchored" data-anchor-id="literature-critique">Literature Critique</h3>
<p>Students in BEE 5850 will select a peer-reviewed journal article related to an application of data analysis and will write a short discussion paper (2-3 pages) analyzing the hypotheses and statistical choices. Students should feel free to select their own paper or can work with Prof.&nbsp;Srikrishnan to identify one of interest, but in all cases should discuss with Prof.&nbsp;Srikrishnan to ensure that the article is appropriate. The discussion paper will be due towards at the end of the semester.</p>
</section>
<section id="readings" class="level3">
<h3 class="anchored" data-anchor-id="readings">Readings</h3>
<p>Readings will be assigned throughout the semester to help students engage with background or uses of the material for that week. These readings will be provided as PDFs on Canvas through Perusall and (when possible through open access or the Cornell library) links from the website. Students are expected to demonstrate engagement with the material through collaborative annotations, whether their own comments on parts of the reading they found interesting or had questions on or responses to other students’ annotations. Students should post overall reflections, synthesizing their takeaways from the reading with content from this or other classes or other experiences, on Ed Discussion. Both the annotations and the reflections should be completed by the start of the first lecture the next week. Students will not be graded on the quantity of annotations, but the degree to which their annotations reflect critical engagement with the reading. One reading assignment will be dropped automatically.</p>
</section>
<section id="homework-assignments" class="level3">
<h3 class="anchored" data-anchor-id="homework-assignments">Homework Assignments</h3>
<p>There will be approximately 4 homework assignments assigned. Homework assignments are intended to be more in-depth applications of course material to data analysis problems.</p>
<p>You will generally have two class weeks to work on an assignment. This is intended to provide you enough time to work on the problem and debug and evaluate your code (including troubleshooting any technical problems); these are not reasons for late submission. Each homework assignment will build on material from the prior classes and possibly from the day the homework is assigned.</p>
<p>Students are encouraged to collaborate and learn from each other on homework assignments, but students must submit their own assignments which represent their own understanding of the material.</p>
<p>Consulting and referencing external resources and your peers is encouraged (engineering is a collaborative discipline!), but plagiarism is a violation of academic integrity.</p>
<p>Some notes on assignment and grading logistics:</p>
<ul>
<li>Homework assignments will be distributed using GitHub Classroom. While GitHub use is not required for the class aside from accepting and cloning assignments, students are encouraged to update their GitHub repositories as they work on the assignments; this helps with answering questions, keeping solutions synced across groups, and gives you a backstop in case something goes wrong and you can’t submit your assignment on time.</li>
<li>Homeworks are due by 9:00pm Eastern Time on the designed due date (usually a Thursday). Your assignment writeup should be submitted to Gradescope as a PDF with the answers to each question tagged (a failure to do this will result in a non-negotiable 10% point deduction).</li>
<li>A meta-rubric is provided on the website, under the Homework page. These are not customized for each assignment but the principles will apply generally.</li>
<li>No homework assignments will be dropped, but you can turn in assignments within 24 hours of the due date with a 50% penalty. If you need a further accomodation for a particular assignment, talk to Prof.&nbsp;Srikrishnan <strong><em>before the due date.</em></strong> Requests for extensions made after the due date will only be considered under extraordinary and unexpected circumstances. Technical challenges submitting assignments are not acceptable reasons for extensions to be granted, and late penalties will apply.</li>
<li><strong>Your submitted homework must stand on its own</strong>! We cannot grade you on the basis of information which was not included in the submitted assignment. While regrade requests should include a justification for why your grade is incorrect, we will not consider explanations or additional reasoning outside of the submission.</li>
</ul>
<p>No homework assignments will be automatically dropped.</p>
</section>
<section id="prelims" class="level3">
<h3 class="anchored" data-anchor-id="prelims">Prelims</h3>
<p>One in-class prelim will be given. The exam is closed-book and closed-note. As a result, the exam will emphasize conceptual material such as model derivations and interpretation of results; any calculations can be done with a pen(cil) and paper. Conflict and extended-time exams will be handled through SDS. Exams will be scanned into Gradescope for grading and feedback.</p>
</section>
<section id="term-project" class="level3">
<h3 class="anchored" data-anchor-id="term-project">Term Project</h3>
<p>Throughout the semester, students will apply the concepts and methods from class to a data set of their choosing. If a student does not have a data set in mind, we will find one which aligns with their interests.</p>
<p>The term project can be completed individually or in groups of 2. There will be three deliverables throughout the semester:</p>
<ul>
<li>A proposal (no more than 2 pages with 11 point font, 1 inch margins, not including figures or references) including:
<ul>
<li>The underlying science question for your project and any associated hypotheses;</li>
<li>The dataset(s) you will analyze and use to test your hypotheses;</li>
<li>Statistical model(s) for the hypotheses and your planned strategy for analysis.</li>
</ul></li>
<li>An interim report (no more than 2 pages with 11 point font, 1 inch margins, not including figures or references) summarizing progress to date, including changes from the original proposal or challenges faced and plans to overcome them.</li>
<li>A final report. The report should be no more than 5 pages (11 point font, 1 inch margins), not including references and figures. More details and rubrics will be provided later in the semester.</li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/envdata\.viveks\.me\/spring2026");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
        for (let i=0; i<annoteTargets.length; i++) {
          const annoteTarget = annoteTargets[i];
          const targetCell = annoteTarget.getAttribute("data-target-cell");
          const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
          const contentFn = () => {
            const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
            if (content) {
              const tipContent = content.cloneNode(true);
              tipContent.classList.add("code-annotation-tip-content");
              return tipContent.outerHTML;
            }
          }
          const config = {
            allowHTML: true,
            content: contentFn,
            onShow: (instance) => {
              selectCodeLines(instance.reference);
              instance.reference.classList.add('code-annotation-active');
              window.tippy.hideAll();
            },
            onHide: (instance) => {
              unselectCodeLines();
              instance.reference.classList.remove('code-annotation-active');
            },
            maxWidth: 300,
            delay: [50, 0],
            duration: [200, 0],
            offset: [5, 10],
            arrow: true,
            trigger: 'click',
            appendTo: function(el) {
              return el.parentElement.parentElement.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'quarto',
            placement: 'right',
            positionFixed: true,
            popperOptions: {
              modifiers: [
              {
                name: 'flip',
                options: {
                  flipVariations: false, // true by default
                  allowedAutoPlacements: ['right'],
                  fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
                },
              },
              {
                name: 'preventOverflow',
                options: {
                  mainAxis: false,
                  altAxis: false
                }
              }
              ]        
            }      
          };
          window.tippy(annoteTarget, config); 
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><span class="faux-block"><i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> 2025 Vivek Srikrishnan</span><br> See the <a href="./about.html">About Page</a> for credit information.</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.en">LICENSE: CC-BY-SA  <i class="fab fa-creative-commons"></i><i class="fab fa-creative-commons-by"></i><i class="fab fa-creative-commons-sa"></i></a>
  </li>  
</ul>
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/bee-envdata-cornell/spring2026/edit/main/syllabus.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/bee-envdata-cornell/spring2026/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Made with <a href="https://julialang.org">Julia</a> and <a href="https://quarto.org/">Quarto</a><br> <a href="https://github.com/bee-envdata-cornell/spring2026">View the source at <i class="fa-brands fa-github" aria-label="github"></i> GitHub</a></p>
</div>
  </div>
</footer>




</body></html>