---
title: "Labs"
tbl-colwidths: [5, 15, 5, 10, 10]  
format:
  html: default
---

This page contains information about and a schedule of the lab assignments for the semester.

## General Information

- You can download each lab notebook through the link below..
- Submit assignments by 9:00pm Eastern Time on the due date on [Gradescope](https://gradescope.com).
- Submissions must be PDFs. Make sure that you tag the pages corresponding to each question; points will be deducted otherwise.
- To convert the assignment notebook to PDF, you can use VS Code to render the notebook to HTML, and then use your browser to print to PDF. If you have set up LaTeX with VS Code, you can convert directly to a PDF.

## Grading

Labs will be graded on a scale of 0-3:

- Missing (0/3): Lab solution is missing or is not responsive to the lab prompt(s);
- Needs Improvement (1/3): Lab is largely incomplete or is missing key concepts;
- Developing (2/3): Lab is mostly complete but may contain major conceptual or implementation errors;
- Acceptable (3/3): Lab is mostly or fully complete without any major errors.

## Schedule

| Lab | Topic | Instructions | Class Date | Due |
|:------:|:------------:|:------:|:------:|:--------:|:--------:|
| Lab 1 | Data Visualization | [{{< fa sharp pen-field >}}](lab01/lab01.qmd) | [{{< fa sharp key-skeleton >}}]{style="color: grey;"} | Jan. 30 | Feb. 2|
| Lab 2 | Causal Reasoning | [{{< fa sharp pen-field >}}]{style="color: grey;"} | Feb. 13 | Feb. 16 |
| Lab 3 | Generalized Linear Models | [{{< fa sharp pen-field >}}]{style="color: grey;"} | Feb. 20 | Feb. 23 |
| Lab 4 | Extreme Values | [{{< fa sharp pen-field >}}]{style="color: grey;"} | Mar. 6 | Mar. 9 |
| Lab 5 | Monte Carlo | [{{< fa sharp pen-field >}}]{style="color: grey;"} | Mar. 20 | Mar. 23 |
| Lab 6 | Missing Data | [{{< fa sharp pen-field >}}]{style="color: grey;"} | Apr. 10 | Apr. 13 |
| Lab 7 | Model Comparison | [{{< fa sharp pen-field >}}]{style="color: grey;"} | Apr. 24 | Apr. 27 |
